//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceModules.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages_da {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_da() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceModules.Errors.ErrorMessages.da", typeof(ErrorMessages_da).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan ikke slette denne oprydningskampagne, da den aktiv.
        /// </summary>
        public static string CleanupCampaign_CannotDeleteActiveCampaign {
            get {
                return ResourceManager.GetString("CleanupCampaign_CannotDeleteActiveCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakten findes ikke i kontaktlisten.
        /// </summary>
        public static string ContactDoesNotExistInContactList {
            get {
                return ResourceManager.GetString("ContactDoesNotExistInContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne kontakt er allerede blevet tilføjet til kontaktlisten..
        /// </summary>
        public static string ContactList_AddContact_ContactAlreadyExitsts {
            get {
                return ResourceManager.GetString("ContactList_AddContact_ContactAlreadyExitsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktlisten du prøver at tilmelde dig kunne ikke findes. Den er måske blevet slettet siden du afmeldte dig..
        /// </summary>
        public static string ContactList_NotFound_UndoUnsubscribe {
            get {
                return ResourceManager.GetString("ContactList_NotFound_UndoUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du afmeldte dig denne kontaktliste for mere end 2 uger siden. Hvis du ønsker at tilmelde dig kontaktlisten igen, skal du gøre det via den oprindelige metode..
        /// </summary>
        public static string ContactList_UndoTokenExpired {
            get {
                return ResourceManager.GetString("ContactList_UndoTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl. Prøv at klikke på linket i e-mailen igen..
        /// </summary>
        public static string ContactList_UndoTokenNotFound {
            get {
                return ResourceManager.GetString("ContactList_UndoTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi kunne finde den kontaktliste du forsøger at afmelde dig fra. Prøv at klikke på linket i e-mailen igen..
        /// </summary>
        public static string ContactList_UnsubscribeTokenEmptyQuery {
            get {
                return ResourceManager.GetString("ContactList_UnsubscribeTokenEmptyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den valgte dato er i fremtiden. Vælg dags dato eller en tidligere dato for at se email-analyser for den valgte dato..
        /// </summary>
        public static string DailyEmailAnalytics_DateMustBeInPast {
            get {
                return ResourceManager.GetString("DailyEmailAnalytics_DateMustBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailen du prøver at tilgå er ikke et nyhedsbrev.
        /// </summary>
        public static string EmailIsNotANewsletter {
            get {
                return ResourceManager.GetString("EmailIsNotANewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl under afsendelse af emailen. Fejlkode: .
        /// </summary>
        public static string EmailSending_Exception {
            get {
                return ResourceManager.GetString("EmailSending_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailen kunne afsendes på nuværende tidspunkt, da brugsgrænsen fastsat af sidens emailudbyder er nået. Prøv venligst igen om en time..
        /// </summary>
        public static string EmailSending_ServiceLimitError {
            get {
                return ResourceManager.GetString("EmailSending_ServiceLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ingen kontakter i kontaktlisten.
        /// </summary>
        public static string EmailSendingToContactList_ContactListMustNotBeEmpty {
            get {
                return ResourceManager.GetString("EmailSendingToContactList_ContactListMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl under dannelse af e-mailen. Prøv igen..
        /// </summary>
        public static string FailedToGenerateEmailBodies {
            get {
                return ResourceManager.GetString("FailedToGenerateEmailBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl. Fejlkode: .
        /// </summary>
        public static string GenericErrorWithErrorCode {
            get {
                return ResourceManager.GetString("GenericErrorWithErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl. Prøv venligst igen..
        /// </summary>
        public static string GenericErrorWithRetryPrompt {
            get {
                return ResourceManager.GetString("GenericErrorWithRetryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl. Vi fandt ikke det du leder efter.
        /// </summary>
        public static string GenericNotFound {
            get {
                return ResourceManager.GetString("GenericNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlingen er ikke gyldig.
        /// </summary>
        public static string GenericValidationError {
            get {
                return ResourceManager.GetString("GenericValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har allerede anmodet om at blive afmeldt nyhedsbreve i denne uge. Du skal bruge det link vi har sendt til din e-mailadresse.
        /// </summary>
        public static string NewletterUnsubscribedNoResultAfterFilteringActiveRequests {
            get {
                return ResourceManager.GetString("NewletterUnsubscribedNoResultAfterFilteringActiveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har allerede bekræftet din tilmelding til ét eller flere nyhedsbreve via dette link.
        /// </summary>
        public static string NewsletterConfirmationTokenAlreadyConfirmed {
            get {
                return ResourceManager.GetString("NewsletterConfirmationTokenAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linket er udløbet. Tilmeld dig venligst nyhedsbrevet igen..
        /// </summary>
        public static string NewsletterConfirmationTokenExpired {
            get {
                return ResourceManager.GetString("NewsletterConfirmationTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprydningskampagnen kunne ikke startes, da det ikke var muligt at finde nogen nyhedsbrevsgrupper.
        /// </summary>
        public static string NewsletterGroupsCleanupCampaign_NoNewsletterGroups {
            get {
                return ResourceManager.GetString("NewsletterGroupsCleanupCampaign_NoNewsletterGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprydningskampagnen kunne ikke startes, da den vil overlappe med en allerede oprettet kampagne.
        /// </summary>
        public static string NewsletterGroupsCleanupCampaign_OverlappingCampaigns {
            get {
                return ResourceManager.GetString("NewsletterGroupsCleanupCampaign_OverlappingCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er ikke tilmeldt nogen nyhedsbreve.
        /// </summary>
        public static string NewsletterRecipientNotSubscribedToAnything {
            get {
                return ResourceManager.GetString("NewsletterRecipientNotSubscribedToAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er allerede tilmeldt alle de valgte nyhedsbreve.
        /// </summary>
        public static string Newsletters_AlreadySubscribedToAllSelected {
            get {
                return ResourceManager.GetString("Newsletters_AlreadySubscribedToAllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi kunne ikke finde en nyhedsbrevsmodtager ud fra det link du fulgte. Prøv igen..
        /// </summary>
        public static string NewsletterSubscriberNotFound {
            get {
                return ResourceManager.GetString("NewsletterSubscriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har forsøgt at tilmelde dig nyhedsbrevet for mange gange. Bekræft din tilmelding via en af de e-mails vi har sendt til din e-mail-adresse.
        /// </summary>
        public static string NewsletterSubscription_TooManyPendingRequests {
            get {
                return ResourceManager.GetString("NewsletterSubscription_TooManyPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er allerede afmeldt.
        /// </summary>
        public static string NewsletterUnsubscribeTokenAlreadyUsed {
            get {
                return ResourceManager.GetString("NewsletterUnsubscribeTokenAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linket i e-mailen er udløbet. Prøv at afmelde dig nyhedsbrevet igen, via hjemmesiden.
        /// </summary>
        public static string NewsletterUnsubscribeTokenExpired {
            get {
                return ResourceManager.GetString("NewsletterUnsubscribeTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlingen er ikke gyldig. Prøv at åbne siden fra linket i e-mailen og prøv igen.
        /// </summary>
        public static string NewsletterUnsubscribeTokenInvalid {
            get {
                return ResourceManager.GetString("NewsletterUnsubscribeTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ikke nogen aktive oprydningskampagner lige nu. Måske er dit link udløbet?.
        /// </summary>
        public static string NoActiveCleanupCampaign {
            get {
                return ResourceManager.GetString("NoActiveCleanupCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemet kunne ikke finde en nyhedsbrevsmodtager med den angivne e-mailadresse.
        /// </summary>
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentagelsesperioden er ugyldig. Slutdato skal være efter startdato.
        /// </summary>
        public static string Reservations_InvalidRecurrencePeriod {
            get {
                return ResourceManager.GetString("Reservations_InvalidRecurrencePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der findes allerede en reservationsanmodning for det valgte tidsrum.
        /// </summary>
        public static string Reservations_ReservationConflict {
            get {
                return ResourceManager.GetString("Reservations_ReservationConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation ikke fundet.
        /// </summary>
        public static string Reservations_ReservationNotFound {
            get {
                return ResourceManager.GetString("Reservations_ReservationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den gentagende reservationsserie blev ikke fundet.
        /// </summary>
        public static string Reservations_SeriesNotFound {
            get {
                return ResourceManager.GetString("Reservations_SeriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den angivne nøgle matcher ikke reservationshistorikken.
        /// </summary>
        public static string Reservations_TokenMismatch {
            get {
                return ResourceManager.GetString("Reservations_TokenMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadressen er ikke gyldig.
        /// </summary>
        public static string SearchContactListsByEmail_InvalidEmail {
            get {
                return ResourceManager.GetString("SearchContactListsByEmail_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det valgte interval for afsendelse af emails er ikke gyldigt.
        /// </summary>
        public static string ServiceLimits_InvalidEmailInterval {
            get {
                return ResourceManager.GetString("ServiceLimits_InvalidEmailInterval", resourceCulture);
            }
        }
    }
}
