//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModules.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModules.Errors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email attachment has no content, making it invalid.
        /// </summary>
        public static string Attachment_BinaryContent_IsEmpty {
            get {
                return ResourceManager.GetString("Attachment_BinaryContent_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email attachment can not be larger than 7.5MB.
        /// </summary>
        public static string Attachment_BinaryContent_TooLarge {
            get {
                return ResourceManager.GetString("Attachment_BinaryContent_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email attachment name must be between 5-256 characters long.
        /// </summary>
        public static string Attachment_Name_InvalidLength {
            get {
                return ResourceManager.GetString("Attachment_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob GUID must not be empty.
        /// </summary>
        public static string BlobStorageFile_BlobGuid_NotEmpty {
            get {
                return ResourceManager.GetString("BlobStorageFile_BlobGuid_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type must not be empty.
        /// </summary>
        public static string BlobStorageFile_ContentType_NotEmpty {
            get {
                return ResourceManager.GetString("BlobStorageFile_ContentType_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name must not be empty.
        /// </summary>
        public static string BlobStorageFile_FileBaseName_NotEmpty {
            get {
                return ResourceManager.GetString("BlobStorageFile_FileBaseName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension contains invalid characters. Only alphanumeric characters are allowed.
        /// </summary>
        public static string BlobStorageFile_FileExtension_Invalid {
            get {
                return ResourceManager.GetString("BlobStorageFile_FileExtension_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension must not be empty.
        /// </summary>
        public static string BlobStorageFile_FileExtension_NotEmpty {
            get {
                return ResourceManager.GetString("BlobStorageFile_FileExtension_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size must be greater than zero.
        /// </summary>
        public static string BlobStorageFile_FileSize_GreaterThanZero {
            get {
                return ResourceManager.GetString("BlobStorageFile_FileSize_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time must be at least an hour after the start time.
        /// </summary>
        public static string BlockedReservationTimeSlot_EndTime_MustBeAfterStart {
            get {
                return ResourceManager.GetString("BlockedReservationTimeSlot_EndTime_MustBeAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must not be in the past.
        /// </summary>
        public static string BlockedReservationTimeSlot_StartTime_InPast {
            get {
                return ResourceManager.GetString("BlockedReservationTimeSlot_StartTime_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of a contact list must be between 5-2000 characters long.
        /// </summary>
        public static string ContactList_Description_InvalidLength {
            get {
                return ResourceManager.GetString("ContactList_Description_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a contact list must be between 3-200 characters long.
        /// </summary>
        public static string ContactList_Name_InvalidLength {
            get {
                return ResourceManager.GetString("ContactList_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email can not have more than 10 attachments.
        /// </summary>
        public static string Email_Attachments_InvalidSize {
            get {
                return ResourceManager.GetString("Email_Attachments_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email attachments must be unique.
        /// </summary>
        public static string Email_Attachments_MustBeUnique {
            get {
                return ResourceManager.GetString("Email_Attachments_MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body content must be at least 20 characters long and the content size must be less than 7MB.
        /// </summary>
        public static string Email_Body_InvalidLength {
            get {
                return ResourceManager.GetString("Email_Body_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total size of the email must be less than 7.5MB.
        /// </summary>
        public static string Email_ContentSize_TooLarge {
            get {
                return ResourceManager.GetString("Email_ContentSize_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email must have between 1-50 recipients.
        /// </summary>
        public static string Email_Recipient_InvalidSize {
            get {
                return ResourceManager.GetString("Email_Recipient_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email recipients must be unique.
        /// </summary>
        public static string Email_Recipients_MustBeUnique {
            get {
                return ResourceManager.GetString("Email_Recipients_MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender address is not approved for sending emails.
        /// </summary>
        public static string Email_SenderAddress_MustBeApproved {
            get {
                return ResourceManager.GetString("Email_SenderAddress_MustBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender address must not be empty.
        /// </summary>
        public static string Email_SenderAddress_MustNotBeEmpty {
            get {
                return ResourceManager.GetString("Email_SenderAddress_MustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject must be between 3-80 characters long.
        /// </summary>
        public static string Email_Subject_InvalidLength {
            get {
                return ResourceManager.GetString("Email_Subject_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description must be between 10 and 5000 characters.
        /// </summary>
        public static string Event_Description_InvalidLength {
            get {
                return ResourceManager.GetString("Event_Description_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description must not be empty.
        /// </summary>
        public static string Event_Description_NotEmpty {
            get {
                return ResourceManager.GetString("Event_Description_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event duration must be at least 15 minutes.
        /// </summary>
        public static string Event_Duration_Minimum15Minutes {
            get {
                return ResourceManager.GetString("Event_Duration_Minimum15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event end time must be after start time.
        /// </summary>
        public static string Event_EndTime_MustBeAfterStart {
            get {
                return ResourceManager.GetString("Event_EndTime_MustBeAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event coordinator is required.
        /// </summary>
        public static string Event_EventCoordinator_NotNull {
            get {
                return ResourceManager.GetString("Event_EventCoordinator_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event location must be between 3 and 50 characters.
        /// </summary>
        public static string Event_Location_InvalidLength {
            get {
                return ResourceManager.GetString("Event_Location_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event location must not be empty.
        /// </summary>
        public static string Event_Location_NotEmpty {
            get {
                return ResourceManager.GetString("Event_Location_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each remote file must be a valid URL.
        /// </summary>
        public static string Event_RemoteFile_InvalidUrl {
            get {
                return ResourceManager.GetString("Event_RemoteFile_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote files must be unique.
        /// </summary>
        public static string Event_RemoteFiles_MustBeUnique {
            get {
                return ResourceManager.GetString("Event_RemoteFiles_MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote files collection must not be null.
        /// </summary>
        public static string Event_RemoteFiles_NotNull {
            get {
                return ResourceManager.GetString("Event_RemoteFiles_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start time must be in the future.
        /// </summary>
        public static string Event_StartTime_MustBeInFuture {
            get {
                return ResourceManager.GetString("Event_StartTime_MustBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title must be between 3 and 100 characters.
        /// </summary>
        public static string Event_Title_InvalidLength {
            get {
                return ResourceManager.GetString("Event_Title_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title must not be empty.
        /// </summary>
        public static string Event_Title_NotEmpty {
            get {
                return ResourceManager.GetString("Event_Title_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event coordinator email address is invalid.
        /// </summary>
        public static string EventCoordinator_EmailAddress_Invalid {
            get {
                return ResourceManager.GetString("EventCoordinator_EmailAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event coordinator name must be between 2 and 100 characters.
        /// </summary>
        public static string EventCoordinator_Name_InvalidLength {
            get {
                return ResourceManager.GetString("EventCoordinator_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event coordinator name must not be empty.
        /// </summary>
        public static string EventCoordinator_Name_NotEmpty {
            get {
                return ResourceManager.GetString("EventCoordinator_Name_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event coordinator phone number is invalid.
        /// </summary>
        public static string EventCoordinator_PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("EventCoordinator_PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must be between 1 and 255 characters.
        /// </summary>
        public static string EventRemoteFile_FileName_InvalidLength {
            get {
                return ResourceManager.GetString("EventRemoteFile_FileName_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must not be empty.
        /// </summary>
        public static string EventRemoteFile_FileName_NotEmpty {
            get {
                return ResourceManager.GetString("EventRemoteFile_FileName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size must be greater than 0 bytes.
        /// </summary>
        public static string EventRemoteFile_FileSize_Invalid {
            get {
                return ResourceManager.GetString("EventRemoteFile_FileSize_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type must be between 1 and 100 characters.
        /// </summary>
        public static string EventRemoteFile_FileType_InvalidLength {
            get {
                return ResourceManager.GetString("EventRemoteFile_FileType_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type must not be empty.
        /// </summary>
        public static string EventRemoteFile_FileType_NotEmpty {
            get {
                return ResourceManager.GetString("EventRemoteFile_FileType_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File URL must be a valid URL.
        /// </summary>
        public static string EventRemoteFile_Url_Invalid {
            get {
                return ResourceManager.GetString("EventRemoteFile_Url_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File URL must not be empty.
        /// </summary>
        public static string EventRemoteFile_Url_NotEmpty {
            get {
                return ResourceManager.GetString("EventRemoteFile_Url_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the newsletter group must be between 5-500 characters long.
        /// </summary>
        public static string NewsletterGroup_Description_InvalidLength {
            get {
                return ResourceManager.GetString("NewsletterGroup_Description_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the newsletter group must be between 3-150 characters long.
        /// </summary>
        public static string NewsletterGroup_Name_InvalidLength {
            get {
                return ResourceManager.GetString("NewsletterGroup_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email cleanup campaign must be at least 2 months long.
        /// </summary>
        public static string NewsletterGroupsCleanupCampaign_CampaignDurationMonths_InvalidDuration {
            get {
                return ResourceManager.GetString("NewsletterGroupsCleanupCampaign_CampaignDurationMonths_InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email cleanup campagin cannot have a start time in the past.
        /// </summary>
        public static string NewsletterGroupsCleanupCampaign_CampaignStart_MustNotBeInThePast {
            get {
                return ResourceManager.GetString("NewsletterGroupsCleanupCampaign_CampaignStart_MustNotBeInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be created because the expiry is set to more than 7 days.
        /// </summary>
        public static string NewsletterSubscriptionAction_Confirmation_AtMost7DaysInFuture {
            get {
                return ResourceManager.GetString("NewsletterSubscriptionAction_Confirmation_AtMost7DaysInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be created because no expiry is defined.
        /// </summary>
        public static string NewsletterSubscriptionAction_Confirmation_NotNull {
            get {
                return ResourceManager.GetString("NewsletterSubscriptionAction_Confirmation_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be created because it has expired.
        /// </summary>
        public static string NewsletterSubscriptionAction_ConfirmationTime_NotAfterExpiry {
            get {
                return ResourceManager.GetString("NewsletterSubscriptionAction_ConfirmationTime_NotAfterExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be created because the initial value is undefined.
        /// </summary>
        public static string NewsletterSubscriptionAction_IsConfirmed_NotNull {
            get {
                return ResourceManager.GetString("NewsletterSubscriptionAction_IsConfirmed_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be created because the token is empty.
        /// </summary>
        public static string NewsletterSubscriptionAction_Token_NotEmpty {
            get {
                return ResourceManager.GetString("NewsletterSubscriptionAction_Token_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one recipient email address is invalid.
        /// </summary>
        public static string Recipient_EmailAddress_MustBeValid {
            get {
                return ResourceManager.GetString("Recipient_EmailAddress_MustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the community must be between 3-75 characters long.
        /// </summary>
        public static string Reservation_CommunityName_InvalidLength {
            get {
                return ResourceManager.GetString("Reservation_CommunityName_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not valid.
        /// </summary>
        public static string Reservation_Email_InvalidStructure {
            get {
                return ResourceManager.GetString("Reservation_Email_InvalidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time must be at least an hour after the start time.
        /// </summary>
        public static string Reservation_EndTime_MustBeAfterStart {
            get {
                return ResourceManager.GetString("Reservation_EndTime_MustBeAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        public static string Reservation_Name_Empty {
            get {
                return ResourceManager.GetString("Reservation_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 3-100 characters long.
        /// </summary>
        public static string Reservation_Name_InvalidLength {
            get {
                return ResourceManager.GetString("Reservation_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can not be empty.
        /// </summary>
        public static string Reservation_PhoneNumber_Empty {
            get {
                return ResourceManager.GetString("Reservation_PhoneNumber_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be between 5-20 characters long.
        /// </summary>
        public static string Reservation_PhoneNumber_InvalidLength {
            get {
                return ResourceManager.GetString("Reservation_PhoneNumber_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must not be in the past.
        /// </summary>
        public static string Reservation_StartTIme_InPast {
            get {
                return ResourceManager.GetString("Reservation_StartTIme_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not valid.
        /// </summary>
        public static string ReservationHistory_Email_InvalidStructure {
            get {
                return ResourceManager.GetString("ReservationHistory_Email_InvalidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation history token cannot be empty.
        /// </summary>
        public static string ReservationHistory_Token_Empty {
            get {
                return ResourceManager.GetString("ReservationHistory_Token_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the reservation location must be between 3-75 characters long.
        /// </summary>
        public static string ReservationLocation_Name_InvalidLength {
            get {
                return ResourceManager.GetString("ReservationLocation_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recurrence interval must be greater than zero.
        /// </summary>
        public static string ReservationSeries_InvalidInterval {
            get {
                return ResourceManager.GetString("ReservationSeries_InvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recurrence end date must be after the start date.
        /// </summary>
        public static string ReservationSeries_InvalidRecurrenceDates {
            get {
                return ResourceManager.GetString("ReservationSeries_InvalidRecurrenceDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recurrence type must be specified.
        /// </summary>
        public static string ReservationSeries_InvalidRecurrenceType {
            get {
                return ResourceManager.GetString("ReservationSeries_InvalidRecurrenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recurrence start date cannot be in the past.
        /// </summary>
        public static string ReservationSeries_StartDateInPast {
            get {
                return ResourceManager.GetString("ReservationSeries_StartDateInPast", resourceCulture);
            }
        }
    }
}
