//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmmelSamvirke.DomainModules.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages_da {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_da() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmmelSamvirke.DomainModules.Errors.ErrorMessages.da", typeof(ErrorMessages_da).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den vedhæftede fil har ikke noget indhold. Filen er derfor ikke gyldig.
        /// </summary>
        public static string Attachment_BinaryContent_IsEmpty {
            get {
                return ResourceManager.GetString("Attachment_BinaryContent_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En vedhæftet fil må ikke være større end 7.5MB.
        /// </summary>
        public static string Attachment_BinaryContent_TooLarge {
            get {
                return ResourceManager.GetString("Attachment_BinaryContent_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den vedhæftede fils navn skal være mellem 5-256 tegn langt.
        /// </summary>
        public static string Attachment_Name_InvalidLength {
            get {
                return ResourceManager.GetString("Attachment_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelsen af en kontaktliste skal være mellem 5-2000 tegn lang.
        /// </summary>
        public static string ContactList_Description_InvalidLength {
            get {
                return ResourceManager.GetString("ContactList_Description_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navnet på en kontaktliste skal være mellem 3-200 tegn langt.
        /// </summary>
        public static string ContactList_Name_InvalidLength {
            get {
                return ResourceManager.GetString("ContactList_Name_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailen kan ikke have mere end 10 vedhæftede filer.
        /// </summary>
        public static string Email_Attachments_InvalidSize {
            get {
                return ResourceManager.GetString("Email_Attachments_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indholdet skal være mindst 20 tegn langt og det må ikke fylde mere end 7MB.
        /// </summary>
        public static string Email_Body_InvalidLength {
            get {
                return ResourceManager.GetString("Email_Body_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailen må ikke overstige en størrelse på 7.5MB.
        /// </summary>
        public static string Email_ContentSize_TooLarge {
            get {
                return ResourceManager.GetString("Email_ContentSize_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailen skal have mellem 1-50 modtagere.
        /// </summary>
        public static string Email_Recipient_InvalidSize {
            get {
                return ResourceManager.GetString("Email_Recipient_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsendingsadressen er ikke godkendt til af sende emails .
        /// </summary>
        public static string Email_SenderAddress_MustBeApproved {
            get {
                return ResourceManager.GetString("Email_SenderAddress_MustBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsendingsadressen må ikke være tom.
        /// </summary>
        public static string Email_SenderAddress_MustNotBeEmpty {
            get {
                return ResourceManager.GetString("Email_SenderAddress_MustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emnefeltet skal være mellem 3-80 tegn langt.
        /// </summary>
        public static string Email_Subject_InvalidLength {
            get {
                return ResourceManager.GetString("Email_Subject_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er mindst én modtager-emailadresse som ikke er gyldig.
        /// </summary>
        public static string Recipient_EmailAddress_MustBeValid {
            get {
                return ResourceManager.GetString("Recipient_EmailAddress_MustBeValid", resourceCulture);
            }
        }
    }
}
