//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmmelSamvirke.ServiceModules.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages_da {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_da() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmmelSamvirke.ServiceModules.Errors.ErrorMessages.da", typeof(ErrorMessages_da).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakten findes ikke i kontaktlisten.
        /// </summary>
        public static string ContactDoesNotExistInContactList {
            get {
                return ResourceManager.GetString("ContactDoesNotExistInContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi kunne finde den kontaktliste du forsøger at afmelde dig fra. Prøv at klikke på linket i e-mailen igen..
        /// </summary>
        public static string ContactList_UnsubscribeTokenEmptyQuery {
            get {
                return ResourceManager.GetString("ContactList_UnsubscribeTokenEmptyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den valgte dato er i fremtiden. Vælg dags dato eller en tidligere dato for at se email-analyser for den valgte dato..
        /// </summary>
        public static string DailyEmailAnalytics_DateMustBeInPast {
            get {
                return ResourceManager.GetString("DailyEmailAnalytics_DateMustBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl under afsendelse af emailen. Fejlkode: .
        /// </summary>
        public static string EmailSending_Exception {
            get {
                return ResourceManager.GetString("EmailSending_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailen kunne afsendes på nuværende tidspunkt, da brugsgrænsen fastsat af sidens emailudbyder er nået. Prøv venligst igen om en time..
        /// </summary>
        public static string EmailSending_ServiceLimitError {
            get {
                return ResourceManager.GetString("EmailSending_ServiceLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ingen kontakter i kontaktlisten.
        /// </summary>
        public static string EmailSendingToContactList_ContactListMustNotBeEmpty {
            get {
                return ResourceManager.GetString("EmailSendingToContactList_ContactListMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl. Fejlkode: .
        /// </summary>
        public static string GenericErrorWithErrorCode {
            get {
                return ResourceManager.GetString("GenericErrorWithErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl. Prøv venligst igen..
        /// </summary>
        public static string GenericErrorWithRetryPrompt {
            get {
                return ResourceManager.GetString("GenericErrorWithRetryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadressen er ikke gyldig.
        /// </summary>
        public static string SearchContactListsByEmail_InvalidEmail {
            get {
                return ResourceManager.GetString("SearchContactListsByEmail_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det valgte interval for afsendelse af emails er ikke gyldigt.
        /// </summary>
        public static string ServiceLimits_InvalidEmailInterval {
            get {
                return ResourceManager.GetString("ServiceLimits_InvalidEmailInterval", resourceCulture);
            }
        }
    }
}
