//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Components.Pages.TechnicalData.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TechnicalDataLocalization_da {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TechnicalDataLocalization_da() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmmelSamvirke2024.Web.Components.Pages.TechnicalData.Localization.TechnicalDataLo" +
                            "calization.da", typeof(TechnicalDataLocalization_da).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kørt fra.
        /// </summary>
        public static string CalledFrom {
            get {
                return ResourceManager.GetString("CalledFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs &amp; data-spor.
        /// </summary>
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indlejret fejlbesked.
        /// </summary>
        public static string ExceptionDialog_InnerException {
            get {
                return ResourceManager.GetString("ExceptionDialog_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stak.
        /// </summary>
        public static string ExceptionDialog_StackTrace {
            get {
                return ResourceManager.GetString("ExceptionDialog_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejldetaljer.
        /// </summary>
        public static string ExceptionDialog_Title {
            get {
                return ResourceManager.GetString("ExceptionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl.
        /// </summary>
        public static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksekveringstid (Højeste).
        /// </summary>
        public static string ExecutionTimeMax {
            get {
                return ResourceManager.GetString("ExecutionTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksekveringstid (Median).
        /// </summary>
        public static string ExecutionTimeMedian {
            get {
                return ResourceManager.GetString("ExecutionTimeMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksekveringstid (ms).
        /// </summary>
        public static string ExecutionTimeMS {
            get {
                return ResourceManager.GetString("ExecutionTimeMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logniveau.
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritisk.
        /// </summary>
        public static string LogLevel_Critical {
            get {
                return ResourceManager.GetString("LogLevel_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejlsøgning.
        /// </summary>
        public static string LogLevel_Debug {
            get {
                return ResourceManager.GetString("LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl.
        /// </summary>
        public static string LogLevel_Error {
            get {
                return ResourceManager.GetString("LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LogLevel_Information {
            get {
                return ResourceManager.GetString("LogLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt.
        /// </summary>
        public static string LogLevel_Unknown {
            get {
                return ResourceManager.GetString("LogLevel_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advarsel.
        /// </summary>
        public static string LogLevel_Warning {
            get {
                return ResourceManager.GetString("LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logniveauer.
        /// </summary>
        public static string LogLevels {
            get {
                return ResourceManager.GetString("LogLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ingen logs at vise for denne periode.
        /// </summary>
        public static string NoLogsFoundMessage {
            get {
                return ResourceManager.GetString("NoLogsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operationer.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlingstype.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessioner.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesrate.
        /// </summary>
        public static string SuccessRate {
            get {
                return ResourceManager.GetString("SuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidslinje over logs.
        /// </summary>
        public static string TimelineTitle_Logs {
            get {
                return ResourceManager.GetString("TimelineTitle_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidslinje over data-spor.
        /// </summary>
        public static string TimelineTitle_Traces {
            get {
                return ResourceManager.GetString("TimelineTitle_Traces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidspunkt.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal kald.
        /// </summary>
        public static string TotalCalls {
            get {
                return ResourceManager.GetString("TotalCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spor.
        /// </summary>
        public static string Traces {
            get {
                return ResourceManager.GetString("Traces", resourceCulture);
            }
        }
    }
}
